### ISSUE TITLE
tritonclient.utils.InferenceServerException: [StatusCode.UNIMPLEMENTED] 

### ISSUE THREAD

**Issue by CPFelix** [isarsoft/yolov4-triton-tensorrt#48]
I had successfully test the engine with standalone TensorRT, but when I tried to run on Triton, I got the error.
“
(yolov4-triton) chen@ubuntu-X785-G30:~/yolov4-triton-tensorrt-1.3.0/clients/python$ python client.py -o data/dog_result.jpg image data/dog.jpg
Traceback (most recent call last):
  File "client.py", line 120, in <module>
    if not triton_client.is_server_live():
  File "/home/chen/anaconda3/envs/yolov4-triton/lib/python3.7/site-packages/tritonclient/grpc/__init__.py", line 217, in is_server_live
    raise_error_grpc(rpc_error)
  File "/home/chen/anaconda3/envs/yolov4-triton/lib/python3.7/site-packages/tritonclient/grpc/__init__.py", line 61, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.UNIMPLEMENTED] 
”
Is the problem relevent with version of grpc?

**Comment by philipp-schmidt** [comment]
Make sure that your triton version matches the version of the tritonclient python pip package that you install.
Check requirements.txt in this repo to see the versioning and compare with your versions of triton and tritonclient
