### ISSUE TITLE
client error

### ISSUE THREAD

**Issue by ontheway16** [isarsoft/yolov4-triton-tensorrt#6]
I have managed to run perf. test with the following:

```
docker run -it --ipc=host --net=host nvcr.io/nvidia/tritonserver:20.08-py3-clientsdk /bin/bash
cd install/bin
./perf_client -m yolov4 -u 127.0.0.1:8001 -i grpc --shared-memory system --concurrency-range 4
```
above is giving 95 inferences, with 2 x 1080Ti

But when I switch to client;
```
qgs@qgs-MS-7A74:~/yolov4-triton-tensorrt/clients/python$ python client.py -h
  File "client.py", line 142
    print(f"Received result buffer of size {result.shape}")
                                                         ^
SyntaxError: invalid syntax

```
its not accepting any parameters etc, directly giving the error.

**Comment by philipp-schmidt** [comment]
make sure you are running the client with a recent version of python, especially python3

**Comment by philipp-schmidt** [comment]
You can btw execute the client on the host and you do not have to execute it inside the tensorrt container. I will add more instructions when the client is done with image and video mode.

**Comment by ontheway16** [comment]
Thanks for the comments. As I remember (also seen from the command prompt, above) I run the client from the host, not from the container. I am not sure about python version, though.. Probably v2.7.

 One more thing, about readme, copying YOLOv4.wts "after" running the container, it could not see the newly copied .wts file within container, may be i did something wrong, but, I stopped the docker, copied file to where it belongs, then rerun docker stuff etc, mixed my mind and struggled a bit. It may help to check order of this operation in readme.

Also, as far as I understand, Triton server does not support inference via curl command, isn't it ?

**Comment by ontheway16** [comment]
An update with python3;
```
qgs@qgs-MS-7A74:~/triton/yolov4-triton-tensorrt/clients/python$ python3 client.py -h
Traceback (most recent call last):
  File "client.py", line 8, in <module>
    import tritonclient.grpc as grpcclient
ModuleNotFoundError: No module named 'tritonclient'

**Comment by philipp-schmidt** [comment]
Yes I had similar issues. Make sure you use the most recent upgrade version of pip and also make sure that your default python binary is python3, because nvidia-pyindex seems to be using python scripts under the hood to update the index.

`ls -al /usr/bin | grep python`

Check to which version the python soft link redirects.

**Comment by ontheway16** [comment]
```
qgs@qgs-MS-7A74:~/triton/yolov4-triton-tensorrt/clients/python$ ls -al /usr/bin | grep python
lrwxrwxrwx  1 root root           26 Mar 26  2018 dh_pypy -> ../share/dh-python/dh_pypy
-rwxr-xr-x  1 root root         1056 Nis 16  2018 dh_python2
lrwxrwxrwx  1 root root           29 Mar 26  2018 dh_python3 -> ../share/dh-python/dh_python3
lrwxrwxrwx  1 root root           23 Tem 20 18:37 pdb2.7 -> ../lib/python2.7/pdb.py
lrwxrwxrwx  1 root root           23 Kas 12  2018 pdb3.5 -> ../lib/python3.5/pdb.py
lrwxrwxrwx  1 root root           23 Tem 17 15:50 pdb3.6 -> ../lib/python3.6/pdb.py
lrwxrwxrwx  1 root root           31 Eki 25  2018 py3versions -> ../share/python3/py3versions.py
-rwxr-xr-x  1 root root          377 Tem 31  2017 pybabel-python3
lrwxrwxrwx  1 root root           26 Mar 26  2018 pybuild -> ../share/dh-python/pybuild
lrwxrwxrwx  1 root root            9 Nis 16  2018 python -> python2.7
lrwxrwxrwx  1 root root            9 Nis 16  2018 python2 -> python2.7
-rwxr-xr-x  1 root root      3665768 Tem 20 18:37 python2.7
lrwxrwxrwx  1 root root           33 Tem 20 18:37 python2.7-config -> x86_64-linux-gnu-python2.7-config
lrwxrwxrwx  1 root root           16 Nis 16  2018 python2-config -> python2.7-config
lrwxrwxrwx  1 root root            9 Eki 25  2018 python3 -> python3.6
-rwxr-xr-x  2 root root      4464368 Kas 12  2018 python3.5
lrwxrwxrwx  1 root root           33 Kas 12  2018 python3.5-config -> x86_64-linux-gnu-python3.5-config
-rwxr-xr-x  2 root root      4464368 Kas 12  2018 python3.5m
lrwxrwxrwx  1 root root           34 Kas 12  2018 python3.5m-config -> x86_64-linux-gnu-python3.5m-config
-rwxr-xr-x  2 root root      4526456 Tem 17 15:50 python3.6
lrwxrwxrwx  1 root root           33 Tem 17 15:50 python3.6-config -> x86_64-linux-gnu-python3.6-config
-rwxr-xr-x  2 root root      4526456 Tem 17 15:50 python3.6m
lrwxrwxrwx  1 root root           34 Tem 17 15:50 python3.6m-config -> x86_64-linux-gnu-python3.6m-config
lrwxrwxrwx  1 root root           16 Eki 25  2018 python3-config -> python3.6-config
-rwxr-xr-x  1 root root          384 Nis 11  2018 python3-futurize
-rwxr-xr-x  1 root root          398 Kas 15  2017 python3-jsonschema
lrwxrwxrwx  1 root root           10 Eki 25  2018 python3m -> python3.6m
lrwxrwxrwx  1 root root           17 Eki 25  2018 python3m-config -> python3.6m-config
-rwxr-xr-x  1 root root          388 Nis 11  2018 python3-pasteurize
lrwxrwxrwx  1 root root           16 Nis 16  2018 python-config -> python2.7-config
lrwxrwxrwx  1 root root           29 Nis 16  2018 pyversions -> ../share/python/pyversions.py
-rwxr-xr-x  1 root root         2971 Tem 20 18:37 x86_64-linux-gnu-python2.7-config
lrwxrwxrwx  1 root root           34 Kas 12  2018 x86_64-linux-gnu-python3.5-config -> x86_64-linux-gnu-python3.5m-config
-rwxr-xr-x  1 root root         3185 Kas 12  2018 x86_64-linux-gnu-python3.5m-config
lrwxrwxrwx  1 root root           34 Tem 17 15:50 x86_64-linux-gnu-python3.6-config -> x86_64-linux-gnu-python3.6m-config
-rwxr-xr-x  1 root root         3283 Tem 17 15:50 x86_64-linux-gnu-python3.6m-config
lrwxrwxrwx  1 root root           33 Eki 25  2018 x86_64-linux-gnu-python3-config -> x86_64-linux-gnu-python3.6-config
lrwxrwxrwx  1 root root           34 Eki 25  2018 x86_64-linux-gnu-python3m-config -> x86_64-linux-gnu-python3.6m-config
lrwxrwxrwx  1 root root           33 Nis 16  2018 x86_64-linux-gnu-python-config -> x86_64-linux-gnu-python2.7-config

**Comment by philipp-schmidt** [comment]
you have to change the softlink to point to python3, aliasing won't help because pip will not run in your bash environment.

Run the next command only if you checked that its valid for you please (check all paths):

`sudo ln -sf /usr/bin/python3 /usr/bin/python`

this will change the python softlink to point to python3

**Comment by ontheway16** [comment]
This one below helped, indeed;
```
sudo pip3 install --upgrade pip

$ python3 -m pip --version
pip 20.2.3 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)

$ pip install nvidia-pyindex
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Collecting nvidia-pyindex
  Using cached nvidia-pyindex-1.0.4.tar.gz (5.0 kB)
Building wheels for collected packages: nvidia-pyindex
  Building wheel for nvidia-pyindex (setup.py) ... done
  Created wheel for nvidia-pyindex: filename=nvidia_pyindex-1.0.4-py3-none-any.whl size=4974 sha256=01dfd1eedda4c63c25684a2daa26a86fd35b713bf3a4e6c7e992ce7a4a3e7083
  Stored in directory: /home/qgs/.cache/pip/wheels/c4/ae/b4/3693ecffe187fb687172bdae75d983489ac88c562dde16220e
Successfully built nvidia-pyindex
Installing collected packages: nvidia-pyindex
Successfully installed nvidia-pyindex-1.0.4
```
But not for client.py, yet.

**Comment by philipp-schmidt** [comment]
Look into the update client README

**Comment by ontheway16** [comment]
Also may worth to notice, 
```
$ curl localhost:8000/api/status/yolov4
```
is giving error 400 on server terminal, and;
```
root@qgs-MS-7A74:/workspace/install/bin# ./perf_client -m yolov4 -u 127.0.0.1:8001 -i grpc --shared-memory system --concurrency-range 4
error: failed to get model metadata: Request for unknown model: 'yolov4' is not found
```
This one above is after succesfully completing both of below;
```
pip install nvidia-pyindex
pip install tritonclient[all]
```

**Comment by ontheway16** [comment]
ok, I have followed the client README,
result is;
```
(base) qgs@qgs-MS-7A74:~/triton/yolov4-triton-tensorrt/clients/python$ conda activate yolov4-triton
(yolov4-triton) qgs@qgs-MS-7A74:~/triton/yolov4-triton-tensorrt/clients/python$ python client.py image data/dog.jpg
FAILED : is_model_ready
```
on Triton terminal;
```
I0922 15:41:32.990915 1 grpc_server.cc:251] Process for ServerLive, rpc_ok=1, 0 step START
I0922 15:41:32.990970 1 grpc_server.cc:251] Process for ServerLive, rpc_ok=1, 0 step COMPLETE
I0922 15:41:32.990984 1 grpc_server.cc:224] Ready for RPC 'ServerLive', 1
I0922 15:41:32.990990 1 grpc_server.cc:349] Done for ServerLive, 0
I0922 15:41:32.991330 1 grpc_server.cc:251] Process for ServerReady, rpc_ok=1, 0 step START
I0922 15:41:32.991349 1 model_repository_manager.cc:492] BackendStates()
I0922 15:41:32.991410 1 grpc_server.cc:251] Process for ServerReady, rpc_ok=1, 0 step COMPLETE
I0922 15:41:32.991425 1 grpc_server.cc:224] Ready for RPC 'ServerReady', 1
I0922 15:41:32.991432 1 grpc_server.cc:349] Done for ServerReady, 0
I0922 15:41:32.991665 1 grpc_server.cc:251] Process for ModelReady, rpc_ok=1, 0 step START
I0922 15:41:32.991678 1 model_repository_manager.cc:559] GetInferenceBackend() 'yolov4' version -1
I0922 15:41:32.991720 1 grpc_server.cc:251] Process for ModelReady, rpc_ok=1, 0 step COMPLETE
I0922 15:41:32.991735 1 grpc_server.cc:224] Ready for RPC 'ModelReady', 1
I0922 15:41:32.991740 1 grpc_server.cc:349] Done for ModelReady, 0
```

**Comment by ontheway16** [comment]
Success, thank you.
```
(yolov4-triton) qgs@qgs-MS-7A74:~/triton/yolov4-triton-tensorrt/clients/python$ python client.py image data/dog.jpg
Running in 'image' mode
Creating buffer from image file...
Invoking inference...
Done
Received result buffer of size (1, 7001, 1, 1)
Naive buffer sum: 43541.35546875
Detected objects: 4
```
